import { CATALOG, type Product } from '../../lib/engine';
// Product imagery: transparent vector renders of the exact case variant (model x colour x
// MagSafe x pack), generated by scripts/gen-cases.mjs into public/img/cases/. Same canvas and
// centring for every file, so thumbnails align in any slot. Original artwork, no third-party assets.
const slug = (s: string) => s.toLowerCase().replace(/\s+/g, '-');
export function caseSrc(p: { compat: string; color: string; magSafe: boolean; pack: number }) {
  return `/img/cases/${slug(p.compat)}_${p.color.toLowerCase()}_${p.magSafe ? 'mag' : 'plain'}_${p.pack === 2 ? 2 : 1}.svg`;
}
// Raster twin of caseSrc() for Google Merchant imageLink (SVG is not accepted); see scripts/gen-cases-png.mjs.
export function casePngSrc(p: { compat: string; color: string; magSafe: boolean; pack: number }) {
  return caseSrc(p).replace('/img/cases/', '/img/cases-png/').replace(/\.svg$/, '.png');
}
const BY_ID = new Map<string, Product>(CATALOG.products.map((p) => [p.id, p]));
export function caseFor(productId: string) {
  const p = BY_ID.get(productId) ?? CATALOG.hero;
  return caseSrc(p);
}
const hero = CATALOG.hero;
export const IMAGES = {
  hero: caseSrc(hero),
  buy: caseSrc(hero),
  sell: caseSrc(hero),
  r1: caseSrc({ ...hero, compat: 'iPhone 16' }),
  r2: caseSrc({ ...hero, compat: 'iPhone 16 Pro Max' }),
  r3: caseSrc({ ...hero, pack: 2 }),
  r4: caseSrc({ ...hero, magSafe: false }),
};
