// Runtime environment for the Worker.
// `Env` (bindings + vars) is generated by `wrangler types` into worker/worker-configuration.d.ts.
// Secrets may be absent at runtime (no-credentials mode), so they are typed here as optional.
export type Secrets = {
  GOOGLE_SA_JSON?: string;
  MERCHANT_ACCOUNT_ID?: string;
  MERCHANT_DATA_SOURCE_ID?: string;
  ADMIN_TOKEN?: string;
  SERPAPI_KEY?: string;
  SEARCH_API_KEY?: string;
  EBAY_CLIENT_ID?: string;
  EBAY_CLIENT_SECRET?: string;
  BESTBUY_API_KEY?: string;
};
// Market ingest / snapshot vars (plain vars in wrangler.jsonc, no secrets). `wrangler types` types them as literals once they are in
// the config; they stay optional here so a deploy without them (or a test env) reads as "not configured" instead of failing to compile.
export type MarketVars = {
  MARKET_RPC_URL?: string;
  MARKET_BOOK?: string;
  MARKET_CHAIN_ID?: string;
  MARKET_DEPLOY_BLOCK?: string;
};
export type AppEnv = Env & Secrets & MarketVars;
export type Fetch = (input: Request | string | URL, init?: RequestInit) => Promise<Response>;
export type Deps = {
  fetch: Fetch;
  nowMs: () => number;
  sleep: (ms: number) => Promise<void>;
  random: () => number;
};
export function defaultDeps(): Deps {
  return {
    fetch: (input, init) => fetch(input, init),
    nowMs: () => Date.now(),
    sleep: (ms) => new Promise((resolve) => setTimeout(resolve, ms)),
    random: () => Math.random(),
  };
}
