import { economics } from '../../../../packages/economics/index.js';
import { matchOffer } from '../../../../packages/matching/index.js';
export const CANON={id:'CASE-IP16PRO-CLEAR-MAG-001',brand:'Apple-compatible',model:'iPhone 16 Pro Clear MagSafe Case',category:'Phone Case',gtin:'850063102441',mpn:'IP16P-CLR-MAG',compatibility:'iPhone 16 Pro',color:'Clear',material:'TPU',packCount:1,attributes:{magsafe:'Yes',packs:'1'}};
export const OFFERS=[
 {img:'buy',id:'of-shopee',source:'shopee',sourceProductId:'SHP-99182',title:'Clear MagSafe Case for iPhone 16 Pro TPU Transparent',url:'#',price:6.82,shipping:0.42,stock:2400,seller:'Supplier A',gtin:'850063102441',attributes:{device:'iPhone 16 Pro',magsafe:'Yes',pack:'1'},observedAt:'12s ago'},
 {img:'sell',id:'of-google',source:'google',sourceProductId:'G-55201',title:'iPhone 16 Pro Clear MagSafe Case TPU',url:'#',price:10.99,shipping:0,stock:800,seller:'Retail buyer market',attributes:{device:'iPhone 16 Pro',magsafe:'Yes',pack:'1'},observedAt:'8s ago'},
 {img:'sell',id:'of-laz',source:'lazada',sourceProductId:'LZ-33012',title:'Wholesale Clear Case iPhone 16 Pro MagSafe TPU',url:'#',price:7.10,shipping:0.35,stock:1200,seller:'Supplier B',attributes:{device:'iPhone 16 Pro',magsafe:'Yes',pack:'1'},observedAt:'20s ago'},
 {img:'r1',id:'r1',source:'shopee',sourceProductId:'R1',title:'Clear Case for iPhone 16 (non-Pro) TPU',url:'#',price:5.10,shipping:.3,stock:500,seller:'X',attributes:{device:'iPhone 16'},observedAt:'1m ago'},
 {img:'r2',id:'r2',source:'lazada',sourceProductId:'R2',title:'Clear MagSafe Case iPhone 16 Pro Max',url:'#',price:7.9,shipping:.3,stock:300,seller:'Y',attributes:{device:'Pro Max'},observedAt:'1m ago'},
 {img:'r3',id:'r3',source:'google',sourceProductId:'R3',title:'Clear MagSafe Case iPhone 16 Pro — 2-Pack',url:'#',price:12.9,shipping:0,stock:200,seller:'Z',attributes:{device:'iPhone 16 Pro',pack:'2-pack'},observedAt:'2m ago'},
 {img:'r4',id:'r4',source:'shopee',sourceProductId:'R4',title:'Clear Case iPhone 16 Pro (no MagSafe ring)',url:'#',price:4.2,shipping:.3,stock:900,seller:'W',attributes:{device:'iPhone 16 Pro'},observedAt:'2m ago'},
];
export function opps(){const e=economics({purchasePrice:6.82,inboundShipping:.42,importDuty:.12,tax:.08,procurementFee:.05,paymentFee:.02,sellPrice:10.99,marketplaceFeeRate:.12,fulfillment:1.10,returnReserveRate:.03,chainCost:.04,units:240,fixedBatch:18});return[{img:'buy',id:'OP-2041',buy:'Shopee',sell:'Google Shopping',buyPx:6.82,landed:+e.landed.toFixed(2),sellPx:10.99,net:+e.net.toFixed(2),margin:+(e.margin*100).toFixed(1),qty:240,ttl:'02:18',status:'READY',score:94.2,match:98.8},{img:'sell',id:'OP-2042',buy:'Lazada',sell:'Google Shopping',buyPx:7.10,landed:7.85,sellPx:10.99,net:2.61,margin:23.7,qty:120,ttl:'01:44',status:'RISK CHECK',score:88.1,match:97.9},{img:'buy',id:'OP-2039',buy:'Shopee',sell:'Lazada Store',buyPx:6.82,landed:7.51,sellPx:9.40,net:1.32,margin:14.0,qty:400,ttl:'00:52',status:'PRICING',score:71.4,match:96.2}]}export const LOTS=[{img:'buy',id:'LOT-1842',units:120,basis:7.51,mkt:10.99,margin:31.7,age:'18m',venue:'Google',status:'LISTED'},{img:'sell',id:'LOT-1841',units:240,basis:7.42,mkt:10.49,margin:29.2,age:'2h',venue:'Shopee Store',status:'INBOUND'},{img:'hero',id:'LOT-1839',units:96,basis:7.60,mkt:10.99,margin:30.8,age:'1d',venue:'Lazada Store',status:'SETTLED'}];
export const POLICY={dailySpendUsd:5000,maxLotUsd:2500,minNetMarginBps:1800,maxQuoteAgeSeconds:180,manualApprovalAboveUsd:1500};
export function matchRows(){return OFFERS.map(o=>({offer:o,m:matchOffer(CANON,{...o,title:o.title,attributes:{...o.attributes,magsafe:o.attributes.pack==='2-pack'?'Yes':(o.id==='r4'?'':'Yes')}})}))}
